from app.config.paths import DOWNLOAD_DIR, LEGACY_HISTORY_FILE as HISTORY_FILE, ROOT_DIR, TOKENS_FILE as TOKEN_FILE
from app.config.settings import DISCORD_BOT_TOKEN, DISCORD_CHANNEL_IDS, DISCORD_EMOJI_DONE, DISCORD_EMOJI_FAILED, DISCORD_EMOJI_QUEUED

INPUT_FILE = str(ROOT_DIR / "dl.txt")
MAX_RETRIES = 10
RETRY_DELAY = 5
DL_DELAY = 5
MAX_DOWNLOAD_THREADS = 5
